### ISSUE TITLE
Support sort by date

### ISSUE THREAD

**Issue by kou** [okkez/redmine_full_text_search#1]
検索結果を日付でもソートできるようにして欲しい。

○○というキーワードを含んだ最新のチケットを見つける、というときに使いたいです。たとえば、「リリース」で検索して最新リリースに関するチケットを見つける、というときに使いたいです。

**Comment by okkez** [comment]
Redmine 本体で検索結果の画面をカスタマイズするようなフックが提供されていないので、すぐにはできなさそうです。
view に手を入れるところまでは、強引になんとかできるかもしれないのですが、コントローラーがかなり厳しいです。

本体の方で対応してもらえるようにパッチを送るかなにかしてみようと思います。

**Comment by kou** [comment]
> 本体の方で対応してもらえるようにパッチを送るかなにかしてみようと思います。

それはとてもよい進め方だと思います！

**Comment by okkez** [comment]
Redmine 3.4.0 で対応してもらえそうです。
http://www.redmine.org/issues/23153

**Comment by okkez** [comment]
Redmine 3.3.1 で対応済みであることを確認した。

**Comment by okkez** [comment]
@kou 検索結果を日付順にソートできるようにしました。

![screenshot from 2016-12-16 17-39-28](https://cloud.githubusercontent.com/assets/33111/21256628/be4c0894-c3b6-11e6-8f36-fd1320e931b3.png)

**Comment by kou** [comment]
あざっす！

試していないんですが、そのラベルだと「スコア」と「更新日時」がなんなのかわかりにくいなぁと思いました。ソートのキーとして「スコア」を使うとか「更新日時」を使うということですよね？

**Comment by okkez** [comment]
はい。そうです。

**Comment by okkez** [comment]
こんなんにしてみました。
![screenshot from 2016-12-16 18-17-06](https://cloud.githubusercontent.com/assets/33111/21257502/f536b1c4-c3bb-11e6-886f-b376bde42882.png)

**Comment by kou** [comment]
そっちの方がわかりやすいと思います！
