### ISSUE TITLE
Score in jounal is ignored

### ISSUE THREAD

**Issue by kou** [okkez/redmine_full_text_search#10]
issueのコメントでのヒット数がスコアに換算されていない。

```sql
if !options[:titles_only] && searchable_options[:search_journals]
  s = ActiveRecord::Base.send(:sanitize_sql_array,
                              search_tokens_condition(columns, tokens, options[:all_words]))
  r |= fetch_ranks_and_ids(
    search_scope(user, projects, options).
    select(:id, "#{s} AS score, #{target_column_name} AS order_target").
    joins(fts_relation).
    joins(:journals).
    joins("INNER JOIN fts_journals ON (journals.id = fts_journals.journal_id)").
    where("#{::Journal.table_name}.private_notes = ? OR (#{::Project.allowed_to_condition(user, :view_private_notes)})", false).
    where(search_tokens_condition(["#{::Journal.table_name}.notes"], tokens, options[:all_words])),
    options[:limit],
    **kw
  )
  queries += 1
end
```

で`#{s} AS score`としているが、`s`はissueの`MATCH AGAINST`であり、コメントの`MATCH AGAINST`ではない。

issueの説明の方がコメントよりも重要だと思うので、issueのスコアはコメントのスコアの10倍重要とかいう感じでスコアを足し合わせるのがよいと思う。

`r |= fetch_ranks_and_ids`だと、スコアが違う場合は同じissueが複数ヒットしたことになるし、そもそもスコアの足し合わせもできないので、このままだとよくない。個人的には`search_result_ranks_and_ids`内の条件は`OR`でつなげてSQL一発でいけないの？と思うけどどうなんだろう。

**Comment by okkez** [comment]
複数ヒットの件は 813f7a86 で対応したつもり。
スコアの調整はまだ。

**Comment by okkez** [comment]
> 個人的にはsearch_result_ranks_and_ids内の条件はORでつなげてSQL一発でいけないの？と思うけどどうなんだろう。

これは無理です。 `search_result_ranks_and_ids` は各モデルのインスタンスメソッドなので `acts_as_searchable` で設定された条件にマッチしたところしか実行されません。

**Comment by kou** [comment]
`search_result_ranks_and_ids`が複数のインスタンスから呼ばれるのでできない、という話をしています？
私は、そうじゃなくて、`search_result_ranks_and_ids`「内」の条件の話をしているつもりでした。言い換えると、一回の`search_result_ranks_and_ids`で複数回`SELECT`しているのを1回の`SELECT`にできないか、という話をしているつもりでした。

**Comment by okkez** [comment]
メインの話題である journal のスコアについては直したので閉じます。
