### ISSUE TITLE
Is limit unused?

### ISSUE THREAD

**Issue by kou** [okkez/redmine_full_text_search#11]
`MATCH AGAINST`で検索している条件に`limit`が付いていない気がする、けど気のせいかしら。
Redmineから値が渡ってきていない？

先頭10件しか返さないときでも`limit`なしで検索されるとムダに重いので表示件数に上限があるときは`limit`付きで検索して欲しい。

**Comment by okkez** [comment]
今の `Redmine::Search` と `acts_as_searchable` の仕様だと必ず limit なしで検索して全件の id を集めてキャッシュに入れてからページネーション等を行うようになっている。
この部分を直すのは、Redmine 本体に手を入れないと厳しいと思う。。。

**Comment by okkez** [comment]
v0.5.0 で limit 付きで検索できるようになった。
