### ISSUE TITLE
Use higher score for project name match

### ISSUE THREAD

**Issue by kou** [okkez/redmine_full_text_search#15]
プロジェクト名にマッチしたら高めのスコアがつくとうれしいです。

「打ち合わせ」で検索して、いろんなプロジェクトでの打ち合わせissueがヒットしたとします。このときにキーワードに「プロジェクト名」を追加して絞り込むと目的のプロジェクトの打ち合わせissueが上の方にくるとうれしいです。

**Comment by okkez** [comment]
v0.5.0 でクエリー構文を使えるようになった。スコアでごにょらなくても `name:@groonga` などとやるとプロジェクト名にマッチしたプロジェクトを検索できる。

**Comment by kou** [comment]
`name:@groonga`って「プロジェクト名でプロジェクトを検索」じゃないですか？
やりたかったのは「プロジェクト名でissue（とかjournalとか）を絞り込み」なんですが、それも`name:@groonga`でできます？

**Comment by kou** [comment]
`search_records`に`project_id`みたいに`project_name`も追加して、`name`は削除しちゃうといいのかしら。

**Comment by okkez** [comment]
`project_name:@groonga` で絞り込みできるようになった。
