### ISSUE TITLE
Highlight doesn't support "OR" and "(...)"

### ISSUE THREAD

**Issue by kou** [okkez/redmine_full_text_search#16]
Groongaは`XXX OR YYY`と書くと`XXX`または`YYY`のどちらかがヒットしたらマッチという挙動になるが、Redmineのハイライト処理は`OR`のことをわからないので`OR`もハイライトしてしまう。

同様に、`(XXX YYY) OR ZZZ`と書くと先に`XXX YYY`を処理してから`(...) OR ZZZ`を評価するのだけれど、これもRedmineのハイライト処理が`(...)`のことをわからないので`(XXX`と`YYY)`をハイライトしようとする。結果として`XXX`と`YYY`はハイライトされない。

Groongaが提供しているハイライト機能を使うといいのだけれど、難しいかしら。

**Comment by okkez** [comment]
Groongaが提供するハイライト機能って `mroonga_snippet_html` や `pgroonga.snippet_html` のことでしょうか。今のRedmineの検索の仕組みのままだとかなり厳しいですね。。。

----
以下、余談。
検索時に使うクエリはスペースで分割された状態でRedmineからこのプラグインに渡ってくる。
そのため `XXX OR YYY` は `%w(XXX OR YYY)` のようになり、Groongaの機能を使った解釈をしていない。
SQLとしては、以下のようになっている。
「すべての単語」のチェックボックスの on/off によって挙動が変わる。

* `MATCH column AGAINST('*D+ XXX OR YYY' IN BOOLEAN MODE)`
* `MATCH column AGAINST('*DOR XXX OR YYY' IN BOOLEAN MODE)`
* `column @@ 'XXX OR YYY'`
* `column @@ 'XXX OR OR OR YYY'` -> エラー！

つまり現状だと、Groonga向けの検索クエリの書き方を有効に使えるようにはなっていない。
たまたま動くものは動く、みたいになっている。

**Comment by kou** [comment]
> Groongaが提供するハイライト機能って `mroonga_snippet_html` や `pgroonga.snippet_html` のことでしょうか。

はい、そうです。

> 今のRedmineの検索の仕組みのままだとかなり厳しいですね。。。

そうですか。。。

**Comment by okkez** [comment]
v0.5.0 で Groonga の `snippet_html` を呼び出すようにしたので解決したはず。
