### ISSUE TITLE
Error during instalation

### ISSUE THREAD

**Issue by nicofff** [okkez/redmine_full_text_search#2]
Got the following error during instalation. Redmine 3.2, ruby 2.0
NoMethodError: private method `prepend' called for #<Class:...

Worked around it by replacing all instances of 
`.prepend(FullTextSearch::Mroonga)`
with 
`.send :prepend , FullTextSearch::Mroonga`

in here: https://github.com/okkez/redmine_full_text_search/blob/master/init.rb#L10

**Comment by okkez** [comment]
Please upgrade your Ruby to 2.1 or later.
Ruby 2.0 is not supported.

**Comment by okkez** [comment]
No response.
