### ISSUE TITLE
Logical NOT is ignored

### ISSUE THREAD

**Issue by kou** [okkez/redmine_full_text_search#25]
Groongaは[`-`で論理否定（その単語が含まれていないという条件）](http://groonga.org/ja/docs/reference/grn_expr/query_syntax.html#logical-not)を指定できますが、検索ボックスで「`Groonga - PostgreSQL`」と指定しても無視され、「Groongaを含むがPostgreSQLは含まない」ではなく「GroongaもPostgreSQLも含む」と解釈されます。

たぶん、Redmineのレベルで1文字のトークンが無視されているから https://github.com/redmine/redmine/blob/master/lib/redmine/search.rb#L63 な気がします。ユーザーからの入力（このクラスの`@question`相当？）をそのままGroongaで解釈できるとうれしいなぁと思います。

なお、回避策として`-`の後に空白を入れずに「`Groonga -PostgreSQL`」とする方法があります。

**Comment by okkez** [comment]
v0.5.0 でクエリー構文を全部使えるようになったはず。
