### ISSUE TITLE
Error on search with "Search titles only"

### ISSUE THREAD

**Issue by nicofff** [okkez/redmine_full_text_search#3]
I get the following sql error

> ActiveRecord::StatementInvalid (Mysql2::Error: Can't find FULLTEXT index matching the column list: SELECT DISTINCT `issues`.`id`, MATCH(fts_issues.subject) AGAINST ('_D+ some search term' IN BOOLEAN MODE) AS score FROM `issues` INNER JOIN `projects` [...] AND (issues.project_id IN (1742)) AND (MATCH(fts_issues.subject) AGAINST ('_D+ some search term' IN BOOLEAN MODE))  ORDER BY score DESC):

**Comment by kou** [comment]
Did you run `bin/rake redmine:plugins:migrate RAILS_ENV=production`?

**Comment by sagastiful** [comment]
Same error happened on MySQL 5.7, while MariaDB 5.5 doesn't cause the error.

**Comment by okkez** [comment]
Could you check Mroonga installation?

See http://mroonga.org/docs/tutorial/installation_check.html

**Comment by okkez** [comment]
No response.
