### ISSUE TITLE
NameError (undefined local variable or method `comments' for FullTextSearch::Model::Callbacks:Class):

### ISSUE THREAD

**Issue by kakaro** [okkez/redmine_full_text_search#42]
ご提供の検索エンジンが社内で大評判です！ありがとうございますm(_ _)m

さっそくですが、
管理　>　設定　>　リポジトリ の「コミットを自動取得する」にチェックを入れてる状態で
プロジェクトのリポジトリに接続しますと、下記のエラーが発生します。

NameError (undefined local variable or method `comments' for FullTextSearch::Model::Callbacks:Class):
  plugins/full_text_search/lib/full_text_search/model.rb:75:in `after_save'
  app/models/repository/subversion.rb:72:in `block (2 levels) in fetch_changesets'
  app/models/repository/subversion.rb:71:in `block in fetch_changesets'
  app/models/repository/subversion.rb:70:in `reverse_each'
  app/models/repository/subversion.rb:70:in `fetch_changesets'
  app/controllers/repositories_controller.rb:86:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Redmine情報は下記の通りです。
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.13.0
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  easy_gantt                     1.9
  full_text_search               0.5.0
  redmine_banner                 0.1.2
  redmine_issue_templates        0.1.8
  view_customize                 1.1.4

では、よろしくお願いします。

**Comment by kakaro** [comment]
plugins/full_text_search/lib/full_text_search/model.rbの７５行目の
short_comments, long_comments = comments.split(/(?:\r?\n)+/, 2).map(&:strip) を
short_comments, long_comments = record.comments.split(/(?:\r?\n)+/, 2).map(&:strip) にしましたら治りました。

**Comment by okkez** [comment]
報告ありがとうございます！
こちらの環境では使っていない部分だったので、直すことができてよかったです！
