### ISSUE TITLE
Unify score for Wiki page

### ISSUE THREAD

**Issue by kou** [okkez/redmine_full_text_search#8]

**Comment by okkez** [comment]
Could you describe more details?

**Comment by kou** [comment]
In 0.2.1, score is computed as separated values `score1` and `score2`: https://github.com/okkez/redmine_full_text_search/blob/v0.2.1/lib/full_text_search/mroonga.rb#L90

And they are summed in Ruby not in MySQL.

These codes are gone now.

**Comment by okkez** [comment]
OK. Thanks!
